---
abstract: 'Simple backups based on rsync'
author:
  - 'John Gravatt <john@gravatt.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Backup-EZ
no_index:
  directory:
    - t
    - inc
requires:
  Config::General: '0'
  Data::UUID: '0'
  File::ShareDir: '0'
  File::Slurp: '0'
  Unix::Syslog: '0'
  perl: '5.006'
version: '0.21'
